### ISSUE TITLE
No Instructions on How to Run Samples Tests

### ISSUE THREAD

**Issue by grant** [googleapis/nodejs-tasks#231]
There should be instructions on how to run the samples tests for this repo:

```sh
npm run samples-test
```

```
  Cloud Task Sample Tests
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    1) should create a queue
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    2) should create a task
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    3) quickstart sample should create a task
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    4) should create a HTTP task
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    5) should create a HTTP task with token
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    6) should delete a queue


  0 passing (3s)
  6 failing
```

Setting up a service account env var didn't seem to work either.

```sh
export GOOGLE_APPLICATION_CREDENTIALS="service_account_location.json"
npm run samples-test
```

Same result. (The Cloud Tasks API is enabled)

---

What am I doing wrong? Ideally I can run these samples or run the tests without much trouble.

**Comment by averikitsch** [comment]
Hi @grant, I realized our Node.js repos don't have this information on the ReadMe, since the ReadMes are being generated. The setup (for credentials) is on the main repo ReadMe and the testing information is included in CONTRIBUTING.MD. With this information, can I close this issue?

**Comment by grant** [comment]
Well, were we able to reproduce the error that I filed above?

This is still a poor developer experience. From a non-Googler perspective, it doesn't matter if these docs are generated or not, I should still be able to run tests. :\

I'd file an error upstream in the generator tracking this issue before closing. How to run the tests for a library shouldn't require looking at the CONTRIBUTING file. We could close this bug referring to that bug instead.
