### ISSUE TITLE
Create HTTP Target tasks fails due to URL issue

### ISSUE THREAD

**Issue by guruvi** [googleapis/nodejs-tasks#264]
I am trying to create a task using the sample code provided here: 

```
const {
  v2beta3: { CloudTasksClient }
} = require("@google-cloud/tasks");

const targetTaskQueue = client.queuePath(
    PROJECT_ID,
    CLOUD_TASK_LOCATION,
    CLOUD_TASK_QUEUE
  );
  const create = async (logTrace, data) => {
    const timeInSeconds = new Date(data.scheduleTime).getTime() / 1000;
    const payload = {
      uuid: data.uuid
    };
    const task = {
      httpRequest: {
        httpMethod: "POST",
        url: TRIGGER_URL,
        headers: {
          ...logTrace,
          "Content-Type": "application/json"
        },
        oidcToken: {
          serviceAccountEmail: AUTH_EMAIL
        },
        body: Buffer.from(JSON.stringify(payload)).toString("base64")
      },
      scheduleTime: {
        seconds: timeInSeconds
      }
    };
    const request = {
      parent: targetTaskQueue,
      task
    };
    
    try {
      const [response] = await client.createTask(request);
      const name = response.name;

      return name;
    } catch (err) {
     
      throw err;
    }


```

It fails with the below error.

`const [response] = await client.createTask(request); ` throws the below error.

```
url.js:154
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object
    at Url.parse (url.js:154:11)
    at Object.urlParse [as parse] (url.js:148:13)
    at ClientHttp2Stream.request.on (/Users/gursivas/Documents/Workspace/scheduler-service/node_modules/@opencensus/instrumentation-http2/build/src/http2.js:105:34)
    at ClientHttp2Stream.contextWrapper (/Users/gursivas/Documents/Workspace/scheduler-service/node_modules/@opencensus/core/build/src/internal/cls-ah.js:72:28)
    at ClientHttp2Stream.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Environment details

"@google-cloud/tasks": "^1.1.2",
"node": ">=10.*" (10.15.3)

Thanks,
GuruVi

**Comment by guruvi** [comment]
Attaching the package.json and package-lock.json files:
[package-lock.json.txt](https://github.com/googleapis/nodejs-tasks/files/3481171/package-lock.json.txt)
[package.json.txt](https://github.com/googleapis/nodejs-tasks/files/3481193/package.json.txt)

Below is the code for creating cloud tasks. This fails with the above error
```const client = new CloudTasksClient();
  const targetTaskQueue = client.queuePath(
    PROJECT_ID,
    CLOUD_TASK_LOCATION,
    CLOUD_TASK_QUEUE
  );
  const create = async (logTrace, data) => {
    const timeInSeconds = new Date(data.scheduleTime).getTime() / 1000;
    const payload = {
      uuid: data.uuid
    };
    const task = {
      httpRequest: {
        httpMethod: "POST",
        url: TRIGGER_URL,
        headers: {
          ...logTrace,
          "Content-Type": "application/json"
        },
        oidcToken: {
          serviceAccountEmail: AUTH_EMAIL
        },
        body: Buffer.from(JSON.stringify(payload)).toString("base64")
      },
      scheduleTime: {
        seconds: timeInSeconds
      }
    };
    const request = {
      parent: targetTaskQueue,
      task
    };
    
    try {
      const [response] = await client.createTask(request);
      const name = response.name;

      return name;
    } catch (err) {
     
      throw err;
    }```

**Comment by guruvi** [comment]
The issue is exactly same as https://github.com/googleapis/nodejs-tasks/issues/247

**Comment by averikitsch** [comment]
Hi @guruvi, I am unable to recreate this error within your specs. How are you passing in the TRIGGER_URL?

**Comment by guruvi** [comment]
1. TRIGGER_URL is of type string. 
2. Hard coded the string for the URL field and still getting the same error.

**Comment by guruvi** [comment]
This issue seems to be different and not related to this package. Hence, closing this ticket.
