### ISSUE TITLE
INVALID_ARGUMENT: Invalid resource field value in the request

### ISSUE THREAD

**Issue by orangezebra** [googleapis/nodejs-tasks#506]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
client issue

2) Did someone already solve this?
no

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: osx 10.15.7
  - Node.js version: 15.7.0
  - npm version: 7.4.3
  - `@google-cloud/tasks` version: 2.3.0

#### Steps to reproduce

  1. Run Nodejs Sample at https://cloud.google.com/tasks/docs/creating-http-target-tasks

I've also tried including my oidcToken as specified in the "w/ auth" section on the same page base on comments in https://github.com/googleapis/nodejs-tasks/issues/394

Error output:

[0] /Users/david/Development/apiv2/node_modules/@grpc/grpc-js/build/src/call.js:31
[0]     return Object.assign(new Error(message), status);
[0]                          ^
[0]
[0] Error: 3 INVALID_ARGUMENT: Invalid resource field value in the request.
[0]     at Object.callErrorFromStatus (/Users/david/Development/apiv2/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
[0]     at Object.onReceiveStatus (/Users/david/Development/apiv2/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
[0]     at Object.onReceiveStatus (/Users/david/Development/apiv2/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
[0]     at Object.onReceiveStatus (/Users/david/Development/apiv2/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
[0]     at /Users/david/Development/apiv2/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78
[0]     at processTicksAndRejections (node:internal/process/task_queues:76:11) {
[0]   code: 3,
[0]   details: 'Invalid resource field value in the request.',
[0]   metadata: Metadata {
[0]     internalRepr: Map(1) {
[0]       'grpc-server-stats-bin' => [
[0]         Buffer(10) [Uint8Array] [
[0]           0, 0, 175, 76, 103,
[0]           0, 0,   0,  0,   0
[0]         ]
[0]       ]
[0]     },
[0]     options: {}
[0]   }
[0] }

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by averikitsch** [comment]
Hi @orangezebra Can you provide how you have modified the code sample?  Based on #394 the error: `INVALID_ARGUMENT: Invalid resource field value in the request.` is due to a misinformed request: `const [ response ] = await tasksClient.createTask({ queuePath, task });`. The sample shows the request object with the correct input fields of parent and task:
```
const request = {parent, task};
const [response] = await client.createTask(request);
```
This is using javascript shorthand that also would expand to:
```
const [response] = await client.createTask({
  parent: queuePath,
  task: my-tasks-object,
});
```

**Comment by orangezebra** [comment]
const TaskClient = () => {
    const tasksClient = new CloudTasksClient();
    const queue = tasksClient.queuePath('<project-name>', 'us-central1', '<queue name>');

    return {
        dispatch: async (payload: string) => {
            const task = {
                httpRequest: {
                  httpMethod: 'POST',
                  url: 'http://google.com',
                  body: Buffer.from(payload).toString('base64'),
                  oidcToken: {
                    serviceAccountEmail: '<service-account-email>',
                  }
                },
                scheduleTime: {
                    seconds: Date.now() / 1000
                }
            };

            const [response] = await tasksClient.createTask({queue, task});
            console.log(`Created task ${response.name}`);
        }
    }
}

    const tasksClient = TaskClient();
    tasksClient.dispatch("Hello World")

**Comment by averikitsch** [comment]
Try updating `const [response] = await tasksClient.createTask({queue, task});` to
```
const [response] = await tasksClient.createTask({parent: queue, task});
```

**Comment by orangezebra** [comment]
D'oh. Thanks, that fixed it.
