### ISSUE TITLE
Random "Error: no such type" errors on creating tasks

### ISSUE THREAD

**Issue by ericalderman-emilio** [googleapis/nodejs-tasks#556]
#### Environment details

  - OS:  Google Cloud Functions
  - Node.js version: 10
  - `@google-cloud/tasks` version: 2.3.6

Randomly, the creation of a task will generate the following error and fail:

```
Error: no such type: google.rpc.ErrorInfo
    at Root.lookupType (/workspace/node_modules/@google-cloud/tasks/node_modules/protobufjs/src/namespace.js:383:15)
    at FallbackErrorDecoder.decodeProtobufAny (/workspace/node_modules/@google-cloud/tasks/node_modules/google-gax/build/src/fallbackError.js:35:32)
    at result.details.status.details.map.detail (/workspace/node_modules/@google-cloud/tasks/node_modules/google-gax/build/src/fallbackError.js:50:56)
    at Array.map (<anonymous>)
    at FallbackErrorDecoder.decodeRpcStatus (/workspace/node_modules/@google-cloud/tasks/node_modules/google-gax/build/src/fallbackError.js:50:37)
    at FallbackErrorDecoder.decodeErrorFromBuffer (/workspace/node_modules/@google-cloud/tasks/node_modules/google-gax/build/src/fallbackError.js:63:46)
    at fetch.then.then (/workspace/node_modules/@google-cloud/tasks/node_modules/google-gax/build/src/fallback.js:357:57)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is my code for task creation:

```
const { v2beta3 } = require("@google-cloud/tasks");
const client = new v2beta3.CloudTasksClient({ fallback: true });
const config = require('./config');
const admin = require("firebase-admin");
const {sendErrorOrder} = require('./mailer.js');

const queue_order = async (payload) => {
    return new Promise(async function (resolve, reject) {
        const serviceAccountEmail = config.default.serviceAccount;
        const project = config.default.projectID;
        const queue = "order-queue";
        const location = "us-central1";
        const url = config.default.processQueueURL;
        const formattedParent = client.queuePath(project, location, queue);
        const task = {
          httpRequest: {
            httpMethod: "POST",
            url: url,
            body: Buffer.from(JSON.stringify(payload)).toString("base64"),
            headers: {
              "Content-Type": "application/json"
            },
            oidcToken: {
              serviceAccountEmail
            }
          }
        };

        const request = {
          parent: formattedParent,
          task: task
        };

        var newTask;
        const call_options = {
          timeout: 200000 // millis
        }
        try {
            newTask = await client.createTask(request, call_options);
            resolve('Success');
        } catch (error) {
            console.log(error);
            console.log('Task creation failed, trying again.');
            try {
                newTask = await client.createTask(request, call_options);
                resolve('Success');
            } catch (error) {
              console.log(error);
              console.log('Task creation failed again, trying one more time.');
              try {
                  newTask = await client.createTask(request, call_options);
                  resolve('Success');
              } catch (error) {
                  console.log('Task creation for order ID ' + payload.id + ' failed, giving up.');
                  await sendErrorOrder(payload.id);
                  reject('Failed');
              }
            }
        }   
    });
}
```

I added the retries to try to address the failures, but sometimes it will still fail all 3 in a row.

**Comment by averikitsch** [comment]
Hi @ericalderman-emilio , can you update to v2:
```diff
- const { v2beta3 } = require("@google-cloud/tasks");
+ const {CloudTasksClient} = require('@google-cloud/tasks');

- const client = new v2beta3.CloudTasksClient({ fallback: true });
+ const client = new CloudTasksClient();
```

Also do you need to set fallback to true?

**Comment by ericalderman-emilio** [comment]
OK I will try that and watch to see if it still happens.

I'm setting fallback to true because of earlier encountering DEADLINE EXCEEDED errors, and this was a suggestion on one of the forums about that.  Do you not recommend it?  Same with setting a timeout in call_options.

Thanks!

**Comment by averikitsch** [comment]
I see. Did updating the library help solve the no such type problem? If it did then you can try adding back in the timeout and fallback.

**Comment by ericalderman-emilio** [comment]
So far I've upgraded the library and left in the timeout and fallback.  So far I haven't seen any errors, but the issue was only happening every few days, so I'll give it some more time.  Do you recommend removing the timeout and fallback?

**Comment by averikitsch** [comment]
The fallback and timeout should be fine if you aren't experiencing the "no such type" error.

**Comment by ericalderman-emilio** [comment]
OK I'll leave them for now then.  Thanks again for the help!
